# /.github/workflows/main.yml
# Warning: deletes all files on uberspace which are not in repo, use without --delete if unsure

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        args: --working-dir=app
        php_version: 7.4
        progress: yes
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude=/app/.env
        path: /
        remote_path: /home/${{ secrets.UBERSPACE_USER }}/html/api/
        remote_host: ${{ secrets.UBERSPACE_HOST }}
        remote_user: ${{ secrets.UBERSPACE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
